font_family JetBrainsMono Nerd Font Mono
font_size 16



disable_ligatures no
enable_audio_bell no

shell zsh
shell_integration disabled

cursor_shape block
url_style curly 
remember_window_size no

background_opacity 0.80
confirm_os_window_close 0
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 

sync_to_monitor no 







# BEGIN_KITTY_THEME
# Base2Tone Meadow Dark
include current-theme.conf
# END_KITTY_THEME