

font_family JetBrainsMono Nerd Font Mono
font_size 16



disable_ligatures no
enable_audio_bell no

shell zsh
shell_integration disabled

cursor_shape beam
cursor_beam_thickness 1.5


cursor_trail 5
cursor_trail_decay 0.05 0.3
cursor_trail_start_threshold 1


scrollback_indicator_opacity 1.0
wheel_scroll_min_lines 1


url_style curly 
remember_window_size no


background_opacity 0.80
dynamic_background_opacity yes
confirm_os_window_close 0
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 

sync_to_monitor no 

# BEGIN_KITTY_THEME
# Cyberpunk Neon
include current-theme.conf
# END_KITTY_THEME
